# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'BuddybossCustomCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  

  # Pods for BuddybossCustomCode

  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

end
